### ISSUE TITLE
eTreasury API integration

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/Dristi_kerala#1]
- [x] Explore HLDs, LLDs @Ajith-beehyv 
- [x] Exploration Integration Document @Ajith-beehyv 
- [x] Create postman collection for all sandbox APIs @Ajith-beehyv 
- [ ] Check production API (do we need to whitelisted production ip) @Ajith-beehyv 
- [ ] Mapping Between eTreasury and solution @Ajith-beehyv 
- [ ] Print the payment(receipt) - DPG has columns to store payment status, payment mode and amount at the channel level @Ajith-beehyv 
- [ ] Re-verification of Payment @Ajith-beehyv

**Comment by PrinceBuduru** [comment]
Done
