### ISSUE TITLE
Sept Demo | Localisation Changes

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/Dristi_kerala#1016]
- [x] Offline payment note:Refer Ticket [Link](https://github.com/orgs/pucardotorg/projects/4/views/13?pane=issue&itemId=77664589)
- [x] Payee Name:Refer Ticket [Link](https://github.com/orgs/pucardotorg/projects/4/views/2?filterQuery=payee&pane=issue&itemId=76559064) 
- [x] Legal Demand Notice:Refer Ticket [Link](https://github.com/orgs/pucardotorg/projects/4/views/2?filterQuery=legal&pane=issue&itemId=76573684)
- [x] Hearing Text:Refer Ticket [Link](https://github.com/orgs/pucardotorg/projects/4/views/2?pane=issue&itemId=79716295)
- [x] Join a case:Refer Ticket [Link](https://github.com/orgs/pucardotorg/projects/4/views/2?pane=issue&itemId=79716664)
- [x] Application localisation:Refer Ticket [Link](https://github.com/orgs/pucardotorg/projects/4/views/2?pane=issue&itemId=79719108)

**Comment by TusharKatiyar2002** [comment]
Fixed in UAT env.

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94
I verified all the changes in solution UAT, and all are updated as expected.

Test Cases:
*Offline payment note:
1)Verify that the confirmation screen displays the message: "Your case file is complete. Kindly note the case file shall be sent for review only after the completion of payments" upon submitting the case file when logged in as both a litigant and an advocate
2) Verify that the note "You will have to make an in person visit to the court if you choose to make payments offline" is displayed on the "Pay to File Case" pop-up when logged in as both a litigant and an advocate.
3)Verify the Display of the Note "Please allow popups to complete the payment" on the "Pay to File Case" Pop-up for Litigant and Advocate
reference link: https://jam.dev/c/48136a97-e50e-46e4-9293-6e107864f375

*Payee Name
Module: E Filing
1) Verify that the header in the "Cheque Details" section is updated from "Name on Cheque" to "Payee Name on Cheque" when logged in as both a litigant and an advocate.
reference link: https://jam.dev/c/854346a7-93d8-41dc-9d34-7d6890eded27

*Legal Demand Notice
Module: E Filing
1)  Verify that the term "Demand Notice" has been updated to "Legal Demand Notice" consistently throughout the E-filing to ensure localization accuracy
reference link: https://jam.dev/c/e230a968-49ce-4875-be74-672f299ad8d1

*Hearing Text
1)Verify that the text "You can join this case online if you are not present in court" is removed, and the "Join Conference" link is placed beside the video camera icon.
reference link: https://jam.dev/c/7265e999-93fa-437b-8616-f42c2bb41a1f

*Join a case
1)Verify that the label "Supporting Advocate" has been correctly changed to "Associate Advocate".
reference link: https://jam.dev/c/6f858062-cba4-4581-b736-5c0d5940af09

*Application localisation
1)Verify that the button labelled "Review Submission" is changed to "Generate Application" in the section of the application.
reference link: https://jam.dev/c/b63614da-be7a-4bed-80a6-d3c797574f7a

Litigant no.7868765756
Advocate no.8798789788
User Ids link: https://docs.google.com/spreadsheets/d/1w0RT8lHfx7T2-WaTW2DS-66THYjtyNYTw-FDoqJp5-o/edit?gid=0#gid=0

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm

**Comment by devarajd94** [comment]
Verified
