### ISSUE TITLE
UAT | Remove the background image in employee login screen

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/Dristi_kerala#1017]
Remove the background image. The court with papers around image.

![Image](https://github.com/user-attachments/assets/8f2c5662-b5c2-428e-b9af-ff1196447056)

**Comment by bhuvanyuguru** [comment]
Resolved in UAT

STEPS TO REPRODUCE: 
> 1) Browse to URL : https://dristi-kerala-uat.pucar.org/digit-ui/employee/user/login
> 2) Check Background Image. **(Verified for above mentioned URL in multiple browsers)**
> 


![Image](https://github.com/user-attachments/assets/e84cfe2f-dd26-4fdf-a4dd-351297444311)

**Comment by devarajd94** [comment]
Verified
