### ISSUE TITLE
Sept Demo | Enable calendar view on holidays/days without hearing

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/Dristi_kerala#1022]
Enable calendar view for days without hearings as well

![Image](https://github.com/user-attachments/assets/acfa8607-5c24-4169-873b-b039f9667990)

**Comment by shambhavigoel1002** [comment]
Changes deployed. @Susmitabe  pls move ticket for testing

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94,
I have verified the issue in the UAT solution environment, and it now correctly displays the calendar view for both 'With Hearing' and 'Without Hearing' cases.
Citizen URL: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/login
Employee URL: https://dristi-kerala-uat.pucar.org/digit-ui/employee/user/login

Test Cases:
1) Verify that the calendar view displays correctly for litigants who do not have any scheduled hearings.
2) Verify that the calendar view displays correctly for advocates who do not have any scheduled hearings.
3) Verify that the calendar view displays correctly for litigants who have one or more scheduled hearings.
4) Verify that the calendar view displays correctly for advocates who have one or more scheduled hearings.
5) Verify that the calendar view displays correctly for judges who have one or more scheduled hearings.
6) Verify that the calendar view displays correctly for judges who do not have any scheduled hearings (Tested in dev env).

Reference links:
Litigant (7876876676) (Not a hearing): https://jam.dev/c/0717cd34-2f40-46ee-a4c5-00d101cfa01c
Advocate (7879979789) (Not a hearing): https://jam.dev/c/22e835aa-44ef-4eca-8c2c-77e2c2411bee
Judge (with multiple hearings): https://jam.dev/c/6a8c9a23-e76e-421f-9c58-f3fc298ace28
Judge (Not a hearing-solution dev): https://jam.dev/c/ea7edf00-25c4-40dd-ab4b-eb99ed146d6f

User Ids link: https://docs.google.com/spreadsheets/d/1w0RT8lHfx7T2-WaTW2DS-66THYjtyNYTw-FDoqJp5-o/edit?gid=0#gid=0

**Comment by devarajd94** [comment]
Verified
