### ISSUE TITLE
Bug | Payment for application made successfully but success screen not shown

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/Dristi_kerala#1064]
Screen: Application submission
Payment made - success shown in E Treasury screen. 
The pop up is closed.
The screen still shows Make Payment screen
The payment is made but success screen is not shown. When the mini window is closed, it shows that the payment is made and pending for review with judge.
https://github.com/user-attachments/assets/1b7c4382-b09d-4d1e-91bc-1fe63580d600

**Comment by shambhavigoel1002** [comment]
Hi @Ajith-beehyv  the billing api is not giving expected response please check

**Comment by shambhavigoel1002** [comment]
Have fixed the changes needed . @rajeshcherukumalli  Please check and confirm

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla,it's working fine_please verify this.

-  Env._UAT
-  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/submissions/submissions-create?filingNumber=F-C.1973.002-2024-000368&applicationNumber=APPLICATION-NO-2024-09-20-000170
-  refernce link: https://jam.dev/c/1d753762-5b7f-429e-b65f-d3666a706eb2
- Test cases:
1.verify that the payment is made success screen is shown.
2.verify that  payment is made and is not pending for review with judge.
3.verify that you have successfully made a submission pop will shown.
4..verify that  payment is made and status will be pending review for judge & advocate.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed

**Comment by devarajd94** [comment]
Verified
