### ISSUE TITLE
Summons and Warrant related APIs

### ISSUE THREAD

**Issue by rkjangid07** [pucardotorg/Dristi_kerala#48]
- [x] Summon template @devarajd94 
- [x] API spec for summons module @rkjangid07 @prasanna2400 @Ajith-beehyv   (Link to DPG summons schema https://github.com/pucardotorg/dristi/blob/main/docs/task/schemas/task-summon.json)
- [x] generate summon document API @Ajith-beehyv 
- [x] send Summons API @Ajith-beehyv 
- [x] DPG - Solution summon integration exploration @Ajith-beehyv 
- [x] Warrants template @devarajd94 
- [x] Adding QR code to Summons Template

**Comment by PrinceBuduru** [comment]
Done
