### ISSUE TITLE
QA || getFileds API ERROR in view case

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#699]
After Joining a case, getting this API ERROR in Parties tab

URL : 
https://dristi-kerala-qa.pucar.org/inbox/v2/_getFields?tenantId=kl&_=1724174643216

Response: {
    "error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[1:81] [bool] failed to parse field [must]"
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[1:81] [bool] failed to parse field [must]",
        "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "field name is null or empty"
        }
    },
    "status": 400
}

CURL : `curl "https://dristi-kerala-qa.pucar.org/inbox/v2/_getFields?tenantId=kl&_=1724174643216" ^
  -H "accept: application/json, text/plain, */*" ^
  -H "accept-language: en-US,en;q=0.8" ^
  -H "content-type: application/json;charset=UTF-8" ^
  -H "origin: https://dristi-kerala-qa.pucar.org" ^
  -H "priority: u=1, i" ^
  -H "referer: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/dristi/home/view-case?caseId=6d3423a2-b188-4aac-8205-42b0f37b51e6" ^
  -H ^"sec-ch-ua: ^\^"Not)A;Brand^\^";v=^\^"99^\^", ^\^"Brave^\^";v=^\^"127^\^", ^\^"Chromium^\^";v=^\^"127^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: same-origin" ^
  -H "sec-gpc: 1" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" ^
  --data-raw ^"^{^\^"SearchCriteria^\^":^{^\^"tenantId^\^":^\^"kl^\^",^\^"moduleName^\^":^\^"Pending Tasks Service^\^",^\^"moduleSearchCriteria^\^":^{^\^"isCompleted^\^":false,^\^"assignedTo^\^":^\^"ae962bc3-4760-4590-b9ae-ad5fcca006b0^\^",^\^"filingNumber^\^":null^},^\^"limit^\^":10000,^\^"offset^\^":0^},^\^"RequestInfo^\^":^{^\^"apiId^\^":^\^"Rainmaker^\^",^\^"authToken^\^":^\^"7b272ace-45b8-4ace-8d91-bb2f24aefc11^\^",^\^"userInfo^\^":^{^\^"id^\^":375,^\^"uuid^\^":^\^"ae962bc3-4760-4590-b9ae-ad5fcca006b0^\^",^\^"userName^\^":^\^"7012345503^\^",^\^"name^\^":^\^"Resp Lit^\^",^\^"mobileNumber^\^":^\^"7012345503^\^",^\^"emailId^\^":null,^\^"locale^\^":null,^\^"type^\^":^\^"CITIZEN^\^",^\^"roles^\^":^[^{^\^"name^\^":^\^"HEARING_VIEWER^\^",^\^"code^\^":^\^"HEARING_VIEWER^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"CASE_VIEWER^\^",^\^"code^\^":^\^"CASE_VIEWER^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"DEPOSITION_VIEWER^\^",^\^"code^\^":^\^"DEPOSITION_VIEWER^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"Citizen^\^",^\^"code^\^":^\^"CITIZEN^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"APPLICATION_CREATOR^\^",^\^"code^\^":^\^"APPLICATION_CREATOR^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"SUBMISSION_DELETE^\^",^\^"code^\^":^\^"SUBMISSION_DELETE^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"DEPOSITION_CREATOR^\^",^\^"code^\^":^\^"DEPOSITION_CREATOR^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"SUBMISSION_RESPONDER^\^",^\^"code^\^":^\^"SUBMISSION_RESPONDER^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"ORDER_VIEWER^\^",^\^"code^\^":^\^"ORDER_VIEWER^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"CASE_EDITOR^\^",^\^"code^\^":^\^"CASE_EDITOR^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"SUBMISSION_CREATOR^\^",^\^"code^\^":^\^"SUBMISSION_CREATOR^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"APPLICATION_VIEWER^\^",^\^"code^\^":^\^"APPLICATION_VIEWER^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"TASK_VIEWER^\^",^\^"code^\^":^\^"TASK_VIEWER^\^",^\^"tenantId^\^":^\^"kl^\^"^},^{^\^"name^\^":^\^"CASE_CREATOR^\^",^\^"code^\^":^\^"CASE_CREATOR^\^",^\^"tenantId^\^":^\^"kl^\^"^}^],^\^"active^\^":true,^\^"tenantId^\^":^\^"kl^\^",^\^"permanentCity^\^":null^},^\^"msgId^\^":^\^"1724174643215^|en_IN^\^",^\^"plainAccessRequest^\^":^{^}^}^}^"`

![Image](https://github.com/user-attachments/assets/c59d30f9-0e60-4fe5-ad3c-12f998ac36b6)

**Comment by prasanna2400** [comment]
Resolved
