### ISSUE TITLE
QA || [BLOCKER] courtstaff case list not shown

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#703]
case list not shown in Court Staff user. 

![Image](https://github.com/user-attachments/assets/c35ad536-2748-46d6-b512-cbed4e6eec10)

**Comment by prasanna2400** [comment]
No task present with the status 'ISSUESUMMON' in task table

**Comment by prasanna2400** [comment]
Status is not updating after payment while creating pending task
@Ajithjaya

**Comment by bhuvanyuguru** [comment]
RESOLVED IN QA
