### ISSUE TITLE
QA || [BLOCKER] Application Search API Error on clicking Submissions Tab

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#713]
After admitting a case, if user clicks on Submissions Tab in View Case, getting this API Error

URL : 
https://dristi-kerala-qa.pucar.org/application/v1/search?_=1724302690885

Response : 
{
    "ResponseInfo": null,
    "Errors": [
        {
            "id": null,
            "parentId": null,
            "code": "APPLICATION_SEARCH_ERR",
            "message": "Error while fetching application list: PreparedStatementCallback; bad SQL grammar [SELECT doc.id as id, doc.documenttype as documenttype, doc.filestore as filestore,doc.documentuid as documentuid, doc.additionaldetails as additionaldetails, doc.application_id as application_id FROM dristi_application_document doc WHERE doc.application_id IN (?)]",
            "description": null,
            "params": null
        }
    ]
}  

CURL : `curl 'https://dristi-kerala-qa.pucar.org/application/v1/search?_=1724302690885' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en;q=0.7' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-qa.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/dristi/home/view-case?caseId=2cb1d3da-2dce-44b2-834f-1c6823d9ddf8&filingNumber=F-C.1973.002-2024-000309&tab=Submissions' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Brave";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  --data-raw '{"criteria":{"filingNumber":"F-C.1973.002-2024-000309","tenantId":"kl"},"RequestInfo":{"apiId":"Rainmaker","authToken":"f736b21f-405a-43a9-b44a-c7026312ed0b","msgId":"1724302690885|en_IN","plainAccessRequest":{}}}'`

![Image](https://github.com/user-attachments/assets/b4438156-3757-4574-b6a5-7670c9d724cf)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

URL: 
https://dristi-kerala-qa.pucar.org/application/v1/search?tenantId=kl&_=1724302690889

Response :

{
    "ResponseInfo": null,
    "Errors": [
        {
            "id": null,
            "parentId": null,
            "code": "APPLICATION_SEARCH_ERR",
            "message": "Error while fetching application list: PreparedStatementCallback; bad SQL grammar [SELECT doc.id as id, doc.documenttype as documenttype, doc.filestore as filestore,doc.documentuid as documentuid, doc.additionaldetails as additionaldetails, doc.application_id as application_id FROM dristi_application_document doc WHERE doc.application_id IN (?)]",
            "description": null,
            "params": null
        }
    ]
}

CURL : `curl 'https://dristi-kerala-qa.pucar.org/application/v1/search?tenantId=kl&_=1724302690889' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en;q=0.7' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-qa.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/dristi/home/view-case?caseId=2cb1d3da-2dce-44b2-834f-1c6823d9ddf8&filingNumber=F-C.1973.002-2024-000309&tab=Submissions' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Brave";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  --data-raw '{"apiOperation":"SEARCH","Individual":{"tenantId":"kl"},"criteria":{"filingNumber":"F-C.1973.002-2024-000309","tenantId":"kl"},"tenantId":"kl","pagination":{"limit":10,"offSet":0},"RequestInfo":{"apiId":"Rainmaker","authToken":"f736b21f-405a-43a9-b44a-c7026312ed0b","msgId":"1724302690889|en_IN","plainAccessRequest":{}}}'`

**Comment by prasanna2400** [comment]
Fixed the issue @bhuvanyuguru , start by creating new application

**Comment by bhuvanyuguru** [comment]
resolved in QA
