### ISSUE TITLE
QA || Update API Error in Court-Staff

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#718]
After successfully E-sign, while closing the request, getting this Update API Error. 

URL: 
https://dristi-kerala-qa.pucar.org/task/v1/update?tenantId=kl

response: {
    "ResponseInfo": null,
    "Errors": [
        {
            "id": null,
            "parentId": null,
            "code": "Error updating task",
            "message": "Error occurred while updating task: null",
            "description": null,
            "params": null
        }
    ]
}

CURL: `curl 'https://dristi-kerala-qa.pucar.org/task/v1/update?tenantId=kl' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en;q=0.5' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-qa.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-qa.pucar.org/digit-ui/employee/orders/Summons&Notice' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Brave";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  --data-raw '{"task":{"id":"0e0d9570-0b93-463c-b585-1d8cf295ae05","tenantId":"kl","orderId":"e58168d2-3999-432e-b179-19ca0692c543","filingNumber":"F-C.1973.002-2024-000309","taskNumber":"TASK-NO-2024-08-22-000028","cnrNumber":"KLJL01-000309-2024","createdDate":"22-08-2024","dateCloseBy":null,"dateClosed":null,"taskDescription":null,"taskType":"SUMMONS","taskDetails":{"caseDetails":{"caseId":null,"caseYear":null,"caseTitle":null,"courtName":"Court of the Judicial First Class Magistrate Kollam","judgeName":"super","caseCharge":null,"hearingDate":null},"summonDetails":{"docType":null,"summonId":null,"issueDate":1724302529370,"partyType":null,"docSubType":null},"warrantDetails":null,"deliveryChannels":{"channelName":"Post","paymentFees":null,"paymentStatus":null,"deliveryStatus":null,"paymentTransactionId":null},"respondentDetails":{"age":null,"name":"Deadpool Vs Wolverine","email":"","phone":"9898989898","state":null,"gender":"","address":{"city":"Hyderabad","state":null,"pincode":"500006","district":"Hyderabad","locality":"Karwan, Girkapalli","coordinate":null},"pinCode":null,"district":null,"relativeName":null,"relationWithRelative":null}},"amount":{"id":"b38e6563-ddb7-42e9-ab24-80626c005b63","amount":"100","type":"FINE","paymentRefNumber":null,"additionalDetails":null,"status":"DONE"},"status":"ISSUESUMMON","assignedTo":null,"isActive":false,"documents":[{"id":"945239fe-049c-4420-8dac-ba239bed0866","documentType":"UNSIGNED","fileStore":"2b475a87-7ced-4955-9b81-3478161fe174","documentUid":"945239fe-049c-4420-8dac-ba239bed0866","additionalDetails":{"fields":[{"key":"FILE_CATEGORY","value":"GENERATE_SUMMONS_DOCUMENT"}],"schema":null,"version":null}}],"additionalDetails":null,"auditDetails":{"createdBy":"1c6e64ae-b300-4347-82be-afa0793759db","lastModifiedBy":"1c6e64ae-b300-4347-82be-afa0793759db","createdTime":1724302529574,"lastModifiedTime":1724302529942},"workflow":{"action":"SERVE","documents":[{}]}},"RequestInfo":{"apiId":"Rainmaker","authToken":"620de025-5898-437f-8455-266cbf3bcaca","userInfo":{"id":372,"uuid":"11ab708c-d696-45a8-a561-6014e612783e","userName":"guruCourt","name":"super","mobileNumber":"1002335566","emailId":null,"locale":null,"type":"EMPLOYEE","roles":[{"name":"HEARING_VIEWER","code":"HEARING_VIEWER","tenantId":"kl"},{"name":"DEPOSITION_EDITOR","code":"DEPOSITION_EDITOR","tenantId":"kl"},{"name":"WORKFLOW_ABANDON","code":"WORKFLOW_ABANDON","tenantId":"kl"},{"name":"ORDER_ESIGN","code":"ORDER_ESIGN","tenantId":"kl"},{"name":"Workflow Admin","code":"WORKFLOW_ADMIN","tenantId":"kl"},{"name":"APPLICATION_CREATOR","code":"APPLICATION_CREATOR","tenantId":"kl"},{"name":"COURT_ROOM_MANAGER","code":"COURT_ROOM_MANAGER","tenantId":"kl"},{"name":"DEPOSITION_PUBLISHER","code":"DEPOSITION_PUBLISHER","tenantId":"kl"},{"name":"TASK_APPROVER","code":"TASK_APPROVER","tenantId":"kl"},{"name":"HEARING_START","code":"HEARING_START","tenantId":"kl"},{"name":"HEARING_APPROVER","code":"HEARING_APPROVER","tenantId":"kl"},{"name":"APPLICATION_RESPONDER","code":"APPLICATION_RESPONDER","tenantId":"kl"},{"name":"SUBMISSION_RESPONDER","code":"SUBMISSION_RESPONDER","tenantId":"kl"},{"name":"ORDER_VIEWER","code":"ORDER_VIEWER","tenantId":"kl"},{"name":"ORDER_REASSIGN","code":"ORDER_REASSIGN","tenantId":"kl"},{"name":"CASE_EDITOR","code":"CASE_EDITOR","tenantId":"kl"},{"name":"TASK_CREATOR","code":"TASK_CREATOR","tenantId":"kl"},{"name":"APPLICATION_APPROVER","code":"APPLICATION_APPROVER","tenantId":"kl"},{"name":"HEARING_DATE_REQUESTOR","code":"HEARING_DATE_REQUESTOR","tenantId":"kl"},{"name":"SUBMISSION_CREATOR","code":"SUBMISSION_CREATOR","tenantId":"kl"},{"name":"Employee","code":"EMPLOYEE","tenantId":"kl"},{"name":"COURT_ADMIN","code":"COURT_ADMIN","tenantId":"kl"},{"name":"CASE_VIEWER","code":"CASE_VIEWER","tenantId":"kl"},{"name":"APPLICATION_REJECTOR","code":"APPLICATION_REJECTOR","tenantId":"kl"},{"name":"ORDER_APPROVER","code":"ORDER_APPROVER","tenantId":"kl"},{"name":"HEARING_CLOSER","code":"HEARING_CLOSER","tenantId":"kl"},{"name":"HEARING_CREATOR","code":"HEARING_CREATOR","tenantId":"kl"},{"name":"ORDER_CREATOR","code":"ORDER_CREATOR","tenantId":"kl"},{"name":"CASE_APPROVER","code":"CASE_APPROVER","tenantId":"kl"},{"name":"DEPOSITION_CREATOR","code":"DEPOSITION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_APPROVER","code":"SUBMISSION_APPROVER","tenantId":"kl"},{"name":"TASK_VIEWER","code":"TASK_VIEWER","tenantId":"kl"},{"name":"HEARING_SCHEDULER","code":"HEARING_SCHEDULER","tenantId":"kl"}],"active":true,"tenantId":"kl","permanentCity":null},"msgId":"1724311320489|en_IN","plainAccessRequest":{}}}'`

![Image](https://github.com/user-attachments/assets/c98d3066-2b60-4902-8106-11a9aa6a95ab)

**Comment by prasanna2400** [comment]
user does not have role to perform the action.

**Comment by bhuvanyuguru** [comment]
resolved in QA
