### ISSUE TITLE
QA || UI issue in Judge's Pending Summons task

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#727]
After successful execution in epost user, judge's pending task is shown as N/A for summons-warrant status modal box.

![Image](https://github.com/user-attachments/assets/5b63829e-b667-4578-aec6-07c8772ab9ff)

**Comment by roopeshsagar** [comment]
![Screenshot from 2024-08-22 16-30-36](https://github.com/user-attachments/assets/67a683cc-b2f1-4509-8815-763a1cff4035)


Its running fine with other cases can you please try with maybe a new case or a fresh example.

**Comment by bhuvanyuguru** [comment]
case issue
