### ISSUE TITLE
UAT || Hearing date UI Issue

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#969]
UI issue in Next hearing date for Judge 

![Image](https://github.com/user-attachments/assets/3f466675-a612-4a55-949b-011b52fa214a)

**Comment by surajmajumdar0001** [comment]
PR: https://github.com/pucardotorg/dristi-solutions/pull/106

![Image](https://github.com/user-attachments/assets/39cf22f3-8883-4d57-af30-7368ea351416)

**Comment by shambhavigoel1002** [comment]
Hi @bhuvanyuguru  Please retest

**Comment by bhuvanyuguru** [comment]
resolved in UAT
